server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        namespace: cfc1e3eb-e7d1-4818-9fbb-212e0be99263
        group: A_GROUP
    gateway:
      discovery:
        locator:
          enabled: true #开启动态路由
          lower-case-service-id: true

