server:
  port: 81 # ?????80
spring:
  application:
    name: login-service
eureka:
  client:
    service-url:
      defaultZonr: http://127.0.0.1/eureka
    registry-fetch-interval-seconds: 3 #?????????????
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}