server:
  port: 8082
spring:
  application:
    name: teacher-service
eureka:
  client:
    service-url:
      defaultZonr: http://127.0.0.1/eureka
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}