server:
  port: 8080
spring:
  application:
    name: nacos-client-a
  cloud:
    nacos: # 如果不指定明明空间会默认注册到public里面去 如果没有指定分组会注册到DEFAULT_GROUP
      server-addr: localhost:8848 #往这个地址去注册自己
      username: nacos
      password: nacos