server:
  port: 8080
spring:
  application:
    name: nacos-client-a
  cloud:
    nacos: # 如果不指定明明空间会默认注册到public里面去 如果没有指定分组会注册到DEFAULT_GROUP
      server-addr: localhost:8848,localhost:8849 #往这个地址去注册自己
      username: nacos
      password: nacos
      discovery:
        namespace: cfc1e3eb-e7d1-4818-9fbb-212e0be99263
        group: A_GROUP
