server:
  port: 80 # 网关一般是80
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      enabled: true #只要加了依赖就会默认开启
      routes:
        - id: login-service-route #这个是路由的id 保持唯一即可
          #uri: http://localhost:8081 #uri同意资源定位符 url同意资源标识符
          uri: lb://login-service
          predicates: #断言是给某一个路由来设定的一种配置规则 默认不能作用在动态路由上
            - Path=/doLogin #匹配规则 只要你path匹配上了/doLogin就往uri转发并i企鹅将路径带上
            - After=2022-06-27T13:58:17.872+08:00[Asia/Shanghai] # 在设定的时间之后才能执行
            - Method=GET,POST #请求方式
            #- Query=name,/^[0-9]{3}[a-z][A-Z]{5}/ #正则表达式
          filters:
            - name: RequestRateLimiter #这个是过滤器的名称
              args: #这个是过滤器的参数
                key-resolver: '#{@ipKeyResolver}' #通过spel表达式取ioc容器中bean的值
                redis-rate-limiter.replenishRate: 1 #生成令牌的速度
                redis-rate-limiter.burstCapacity: 3 #桶容量
      discovery:
        locator:
          enabled: true #开启动态路由 开启通用应用名称 找到服务的功能
          lower-case-service-id: true # 开启服务名称小写
      globalcors: #配置跨域
        corsConfigurations:
          '[/**]':
            allowCredebtials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOrigins: '*'
eureka:
  client:
    service-url:
      defaultZonr: http://127.0.0.1/eureka
    registry-fetch-interval-seconds: 3 #?????????????
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}