server:
  port: 80 # ?????80
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      enabled: true #?????? ????
      routes:
        - id: login-service-route #??id.????
          #uri: http://localhost:8081 #uri??????? url???????
          uri: lb://login-service
          predicates: #?????????????,????????????
            - Path=/doLogin #???? ??Path????,doLogin??uri?????????
            - After=2022-06-27T13:58:17.872+08:00[Asia/Shanghai] # ????????????
            - Method=GET,POST #??????
            - Query=name,/^[0-9]{3}[a-z][A-Z]{5}/ #????????????????
      discovery:
        locator:
          enabled: true #?????? ???????? ???????
          lower-case-service-id: true # ????????
eureka:
  client:
    service-url:
      defaultZonr: http://127.0.0.1/eureka
    registry-fetch-interval-seconds: 3 #?????????????
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}